/***********************************************************************************************
** Program name: Lab 10
** Author: Jordan Hamilton
** Date: 12/1/2018
** Description: This program displays a menu asking the user to add an integer to the end of a
** queue in a new node, display the integer data member of the node at the front of the queue,
** remove the node at the front of the queue, display the values of all nodes in the queue, or
** quit the program. A method in the Queue object performs the appropriate action on a
** circular linked list based on the user's choice.
***********************************************************************************************/

#include <cstdlib>
#include <iostream>
#include <memory>
#include <string>

#include "Menu.hpp"
#include "Game.hpp"

using std::cout;
using std::endl;
using std::string;
using std::unique_ptr;

void populateMenu(unique_ptr<Menu> &menu);

/***********************************************************************************************
** Description: This program can be run via the finalproject executable generated by make.
***********************************************************************************************/
int main() {

  int choice;
  string scenario;
  Game newGame;

  unsigned seed = time(0);
  srand(seed);

  unique_ptr<Menu> mainMenu( new Menu() );
  populateMenu(mainMenu);

  scenario = "\nWelcome to Search & Rescue!\n\nYou're a wilderness survival expert searching for \
a lost hiker.\nYour goal is to explore the wilderness in search of the lost hiker before you \
run out of energy.\n";

  do {

    choice = mainMenu->getIntFromPrompt(scenario, 1, mainMenu->getMenuChoices(), true);

    cout << endl;

    switch (choice)  {

      case 1 : cout << "New game begins now!" << endl;

      default : {}

    }

    cout << endl;

  } while( choice != mainMenu->getMenuChoices() );

  mainMenu = nullptr;

  return 0;

}


/***********************************************************************************************
** Description: This function takes a pointer to a Menu object, then calls the addMenuItem
** method to add the approprate menu options to the program's menu.
***********************************************************************************************/
void populateMenu(unique_ptr<Menu> &menu) {

  menu->addMenuItem("Begin a new game");
  menu->addMenuItem("Exit");

}
